spring:
  application:
    name: mcp-weather-server
  ai:
    mcp:
      server:
        name: mcp-weather-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        stdio: false
  main:
    banner-mode: off

server:
  port: 9010

